
package co.gov.ugpp.parafiscales.servicios.liquidador.srvaplhojacalculoliquidacion;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "portSrvAplHojaCalculoLiquidacion", targetNamespace = "http://www.ugpp.gov.co/Liquidador/SrvAplHojaCalculoLiquidacion")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    co.gov.ugpp.parafiscales.servicios.liquidador.contextorespuestatipo.v1.ObjectFactory.class,
    co.gov.ugpp.parafiscales.servicios.liquidador.contextotransaccionaltipo.v1.ObjectFactory.class,
    co.gov.ugpp.parafiscales.servicios.liquidador.criterioordenamientotipo.v1.ObjectFactory.class,
    co.gov.ugpp.parafiscales.servicios.liquidador.errortipo.v1.ObjectFactory.class,
    co.gov.ugpp.parafiscales.servicios.liquidador.fallotipo.v1.ObjectFactory.class,
    co.gov.ugpp.parafiscales.servicios.liquidador.identificaciontipo.v1.ObjectFactory.class,
    co.gov.ugpp.parafiscales.servicios.liquidador.archivotipo.v1.ObjectFactory.class,
    co.gov.ugpp.parafiscales.servicios.liquidador.expedientetipo.v1.ObjectFactory.class,
    co.gov.ugpp.parafiscales.servicios.liquidador.seriedocumentaltipo.v1.ObjectFactory.class,
    co.gov.ugpp.parafiscales.servicios.liquidador.conceptocontabletipo.v1.ObjectFactory.class,
    co.gov.ugpp.parafiscales.servicios.liquidador.detallehojacalculotipo.v1.ObjectFactory.class,
    co.gov.ugpp.parafiscales.servicios.liquidador.hojacalculotipo.v1.ObjectFactory.class,
    co.gov.ugpp.parafiscales.servicios.liquidador.srvaplhojacalculoliquidacion.ObjectFactory.class
    
        
    //AQUI METER ESAS 5 CLASES QUE FALTAN PARA DESCARTAR QUE ESO PRODUSCA EL ERROR   
        
    //co.gov.ugpp.esb.schema.departamentotipo.v1.ObjectFactory.class,
    //co.gov.ugpp.esb.schema.municipiotipo.v1.ObjectFactory.class,  
    //    co.gov.ugpp.schema.gestiondocumental.documentotipo.v1.ObjectFactory.class,    
    //    co.gov.ugpp.schema.gestiondocumental.metadatadocumentotipo.v1.ObjectFactory.class,    
        //    co.gov.ugpp.schema.liquidaciones.aportesindependientetipo.v1.ObjectFactory.class,
})
public interface PortSrvAplHojaCalculoLiquidacion {


    /**
     * 
     * @param msjOpConsultarPorIdSol
     * @return
     *     returns co.gov.ugpp.liquidador.srvaplhojacalculoliquidacion.OpConsultarPorIdResTipo
     * @throws MsjOpConsultarPorIdFallo
     */
    @WebMethod(operationName = "OpConsultarPorId", action = "http://www.ugpp.gov.co/Liquidador/SrvAplHojaCalculoLiquidacion/OpConsultarPorId")
    @WebResult(name = "OpConsultarPorIdRes", targetNamespace = "http://www.ugpp.gov.co/Liquidador/SrvAplHojaCalculoLiquidacion", partName = "msjOpConsultarPorIdRes")
    public OpConsultarPorIdResTipo opConsultarPorId(
        @WebParam(name = "OpConsultarPorIdSol", targetNamespace = "http://www.ugpp.gov.co/Liquidador/SrvAplHojaCalculoLiquidacion", partName = "msjOpConsultarPorIdSol")
        OpConsultarPorIdSolTipo msjOpConsultarPorIdSol)
        throws MsjOpConsultarPorIdFallo
    ;

    /**
     * 
     * @param msjOpGenerarExcelSol
     * @return
     *     returns co.gov.ugpp.liquidador.srvaplhojacalculoliquidacion.OpGenerarExcelResTipo
     * @throws MsjOpGenerarExcelFallo
     */
    @WebMethod(operationName = "OpGenerarExcel", action = "http://www.ugpp.gov.co/Liquidador/SrvAplHojaCalculoLiquidacion/OpGenerarExcel")
    @WebResult(name = "OpGenerarExcelRes", targetNamespace = "http://www.ugpp.gov.co/Liquidador/SrvAplHojaCalculoLiquidacion", partName = "msjOpGenerarExcelRes")
    public OpGenerarExcelResTipo opGenerarExcel(
        @WebParam(name = "OpGenerarExcelSol", targetNamespace = "http://www.ugpp.gov.co/Liquidador/SrvAplHojaCalculoLiquidacion", partName = "msjOpGenerarExcelSol")
        OpGenerarExcelSolTipo msjOpGenerarExcelSol)
        throws MsjOpGenerarExcelFallo
    ;

}
