
package co.gov.ugpp.parafiscales.servicios.liquidador.srvaplliquidacion;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "portSrvAplLiquidador", targetNamespace = "http://www.ugpp.gov.co/Liquidador/SrvAplLiquidador")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    co.gov.ugpp.parafiscales.servicios.liquidador.srvaplliquidacion.ObjectFactory.class,
    co.gov.ugpp.parafiscales.servicios.liquidador.errortipo.v1.ObjectFactory.class,
    co.gov.ugpp.parafiscales.servicios.liquidador.fallotipo.v1.ObjectFactory.class,
    co.gov.ugpp.parafiscales.servicios.liquidador.identificaciontipo.v1.ObjectFactory.class,
    co.gov.ugpp.parafiscales.servicios.liquidador.archivotipo.v1.ObjectFactory.class,
    co.gov.ugpp.parafiscales.servicios.liquidador.expedientetipo.v1.ObjectFactory.class,
    co.gov.ugpp.parafiscales.servicios.liquidador.seriedocumentaltipo.v1.ObjectFactory.class,
    co.gov.ugpp.parafiscales.servicios.liquidador.conceptocontabletipo.v1.ObjectFactory.class,
    co.gov.ugpp.parafiscales.servicios.liquidador.detallehojacalculotipo.v1.ObjectFactory.class,
    co.gov.ugpp.parafiscales.servicios.liquidador.hojacalculotipo.v1.ObjectFactory.class
})
public interface PortSrvAplLiquidador {


    @WebMethod(operationName = "OpLiquidar", action = "http://www.ugpp.gov.co/Liquidador/SrvAplLiquidador/OpLiquidar")
    @WebResult(name = "OpLiquidarRes", targetNamespace = "http://www.ugpp.gov.co/Liquidador/SrvAplLiquidador", partName = "msjOpLiquidarRes")
    public OpLiquidarResTipo opLiquidar(
        @WebParam(name = "OpLiquidarSol", targetNamespace = "http://www.ugpp.gov.co/Liquidador/SrvAplLiquidador", partName = "msjOpLiquidarSol")
        OpLiquidarSolTipo msjOpLiquidarSol)
        throws MsjOpLiquidarFallo
    ;

}
